### ISSUE TITLE
Failed to verify bitcode

### ISSUE THREAD

**Issue by JaehoJu** [naver/naveridlogin-sdk-ios#1]
Xcode 9.1 을 사용하고 있습니다. archive 시에 다음의 오류가 발생합니다. bitcode 활성화가 필요해보입니다. Build Setting 에서 Enable Bitcode 를 YES 로 활성화해도 문제는 해결되지 않습니다.

Failed to verify bitcode in NaverThirdPartyLogin.framework/NaverThirdPartyLogin:
error: Bundle only contains bitcode-marker /var/folders/8g/sc91gmp14s91pxvs98kwp9rh0000gn/T/XcodeDistPipeline.Rw7/Root/Payload/Abc.app/Frameworks/NaverThirdPartyLogin.framework/NaverThirdPartyLogin (armv7)

**Comment by dukeow94** [comment]
같은 상황입니다.

**Comment by JaehoJu** [comment]
이번 업데이트로 네이버 라이브러리 파일이 기존(앱) 프로젝트에 속해 있다가 Pods 프로젝트로 옮겨갔습니다. 라이브러리가 위치하는 프로젝트가 바뀌었을 뿐인데 bitcode 문제가 발생했습니다. 이게 이상해서 [otool](https://stackoverflow.com/questions/32808642/how-to-check-if-a-framework-is-bitcode-supported-for-xcode7) 을 이용해 바로 이전 버전인 4.0.7 버전과 bitcode 지원 여부를 비교해봤습니다. [버전 4.0.7](https://developers.naver.com/docs/login/sdks/) 에서는 libNaverLogin.a 파일, [버전 4.0.8](https://github.com/naver/naveridlogin-sdk-ios) 에서는 NaverThirdPartyLogin 파일, 둘을 비교해봤는데요.
- **libNaverLogin.a 파일** (architecture: i386 _armv7_ _armv7s_ x86_64 _arm64_)에서는 bitcode 가
 _armv7_, _armv7s_, _arm64_ 에 있는 것으로 확인됐고
- **NaverThirdPartyLogin 파일** (architecture: i386 x86_64 armv7 arm64)에서는 bitcode 가 어떤 architecture 에도 없는 것으로 확인됐습니다.

bitcode 가 4.0.7 버전까지는 지원되다가 4.0.8 버전부터 지원되지 않고 있는 것 같습니다.
[Apple 문서](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html)에 다음과 같은 글이 있습니다. 제가 개발하고 앱이 bitcode 를 제공하려면 모든 앱이나 프레임워크들이 bitcode 를 같이 포함해야 한다는 것인데요. 확인 및 지원 부탁드리겠습니다.

> For iOS apps, bitcode is the default, but optional. For watchOS and tvOS apps, bitcode is required. If you provide bitcode, all apps and frameworks in the app bundle (all targets in the project) need to include bitcode.

**Comment by HanBin-Kim** [comment]
4.0.9버전에서 패치 완료 되었습니다.

**Comment by SeungIlWoo** [comment]
4.1.2 에서 bitcode가 지원되지 않습니다. 
아키텍쳐 확인은 안해봤지만 fastlane에서 걸리는데 확인 부탁 드립니다.
