### ISSUE TITLE
in iOS13 work error.

### ISSUE THREAD

**Issue by danwey** [naver/naveridlogin-sdk-ios#10]
SDKversion:4.4.2
when vc is present viewController.

[[NCSDKManager getSharedInstance] setParentViewController:vc];
will work erorr.
1. unfounded close-button .
2.main-view can't again open when close the view.

**Comment by HanBin-Kim** [comment]
@danwey 

Hello, danwey 
I think so, you used [cafe-sdk-ios](https://github.com/naver/cafe-sdk-ios) :)

**Comment by danwey** [comment]
ok
