### ISSUE TITLE
[[NaverThirdPartyLoginConnection getSharedInstance] resetToken] is not work

### ISSUE THREAD

**Issue by Miko-J** [naver/naveridlogin-sdk-ios#12]
I use the latest library, but the [[NaverThirdPartyLoginConnection getSharedInstance] resetToken] doesn't work, safi will automatically record the last login account information, log in directly

**Comment by HanBin-Kim** [comment]
@Miko-J 
Hi, Miko 
Hello, we are using SFSafariViewController to share Safari's cookie storage. This method( [[NaverThirdPartyLoginConnection getSharedInstance] resetToken]) is intended to remove tokens and associations within the app.
You can't remove a user's login to Safari.
