### ISSUE TITLE
NaverThirdPartyLoginConnectionDelegate 프로토콜 method 중에 오탈자

### ISSUE THREAD

**Issue by SiUkLee** [naver/naveridlogin-sdk-ios#13]
- (void)oauth20Connection:(NaverThirdPartyLoginConnection *)oauthConnection didFailAuthorizationWithRecieveType:(THIRDPARTYLOGIN_RECEIVE_TYPE)**recieveType**;
- (void)oauth20Connection:(NaverThirdPartyLoginConnection *)oauthConnection didFinishAuthorizationWithResult:(THIRDPARTYLOGIN_RECEIVE_TYPE)**recieveType**;

recieveType -> receiveType

**Comment by HanBin-Kim** [comment]
안녕하세요. 기수정 완료되었습니다. 감사합니다
