### ISSUE TITLE
use NaverThirdPartyLogin.framework can't upload  to AppStore

### ISSUE THREAD

**Issue by Miko-J** [naver/naveridlogin-sdk-ios#15]
The old SDK contains uiwebview and has system bugs. When we use the naverthirdpartylogin.framework of GitHub, we find that the upload Appstore reports errors, including the unsupported architectures i386 and x86 ʄ. I hope it can be fixed. Thank you.

**Comment by HanBin-Kim** [comment]
@Miko-J 
Hi. I think it will be resolved if you download the latest version(4.1.1) of the SDK through cocoapods. 
Thanks 👍
