### ISSUE TITLE
Scheme 오류

### ISSUE THREAD

**Issue by JaehoJu** [naver/naveridlogin-sdk-ios#2]
NaverThirdPartyConstatnsForApp.h 파일에서 kServiceAppUrlScheme 상수값, 즉 scheme 에 대해서 문제가 있는 것 같습니다. 앱에서 네이버 앱으로 인증할 때와 사파리 뷰컨트롤러로 인증할 때에 차이가 있습니다. 등록된 scheme 이 "Abc" 일 때, 사파리 뷰컨트롤러로 인증하면 콜백으로 받는 url 의 scheme 이 "abc" 입니다. 대문자 A 가 소문자 a 로 바뀝니다. 따라서 사파리 뷰컨트롤러에서 네이버 로그인을 한 뒤에 액션(화면 이동)이 이어질 수 없는 문제가 있습니다.

**Comment by HanBin-Kim** [comment]
안녕하세요. @JaehoJu님

4.0.8버전의 네이버 로그인은 SFSafariViewcontroller를 사용하고있습니다.
Safari는 RFC 1808와 RFC 1738를 따르도록 만들어져 있습니다.

Scheme names consist of a sequence of characters. The lower case letters "a"--"z", digits, and the characters plus ("+"), period ("."), and hyphen ("-") are allowed. For resiliency, programs interpreting URLs should treat upper case letters as equivalent to lower case in scheme names (e.g., allow "HTTP" as well as "http").

**Comment by JaehoJu** [comment]
상세한 설명과 답변에 감사드립니다!
