### ISSUE TITLE
May provide M1 support SDK?

### ISSUE THREAD

**Issue by LeePoHsien** [naver/naveridlogin-sdk-ios#20]
Hi naver development team,

May provide M1 support SDK? our project is blocked to do development on M1 machine.

Currently **naveridlogin-sdk-ios** SDK lack of architecture for arm64 simulator, so it's unable to do development with M1 macBook.

Please help to release your SDK with M1 architecture machine, the SDK should auto contain arm64 simulator.

Thanks and regards,
Allen

**Comment by LeePoHsien** [comment]
Hello any body here can give response for issues?
@ksmail13 
@beanmilk 
@mydamyda 
@reflect87 
@HanBin-Kim

**Comment by HanbinKim** [comment]
@LeePoHsien  
Hello, 
m1 architecture support is being prepared.
Before that, please use Rosetta.

It will be distributed during this month.

Thanks

**Comment by comeonyoh** [comment]
please update this library …

**Comment by innocarpe** [comment]
많은 SDK 들 중에 정말 딱 이거 하나만 M1 지원을 안하고 있습니다. M1 대응을 언제로 생각하고 있으신지 궁금해요.

**Comment by l1004ga** [comment]
@HanbinKim @beanmilk 
M1 대응 언제 될까요 ㅠㅠㅠ xcode simulator 에서 작동이 안되네요 ㅠ,ㅠ
