### ISSUE TITLE
SPM 미지원 이슈

### ISSUE THREAD

**Issue by devming** [naver/naveridlogin-sdk-ios#21]
안녕하세요

네아로 SPM 지원해주시면 정말 좋을 것 같은데 별도의 계획이 있으신지 궁금합니다.

**Comment by gooson** [comment]
정말 필요합니다.

**Comment by comeonyoh** [comment]
정말 필요합니다2

**Comment by kyungkoo** [comment]
임사방편으로 
https://github.com/kyungkoo/naveridlogin-ios-sp
이렇게 사용해 보는건 어떨까요.

**Comment by cheeselemon** [comment]
빨리 해주세요 2023년 돼가요!

**Comment by cheeselemon** [comment]
빨리 해주세요 2023년임!!

**Comment by ebPark9511** [comment]
SPM 지원 부탁드립니다 ㅠ ㅠ pod 없애고 싶어요..

**Comment by cheeselemon** [comment]
> 임사방편으로 https://github.com/kyungkoo/naveridlogin-ios-sp 이렇게 사용해 보는건 어떨까요.

참고로 이걸로 하면 가능은 합니다. 감사해요 @kyungkoo
