### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by kotran88** [naver/naveridlogin-sdk-ios#22]
`Stripped /Users/jangjinhyeog/Library/Developer/Xcode/DerivedData/beauket-aovymeokscfmzedgudszpmmcpehv/Build/Products/Debug-iphoneos/beauket.app/Frameworks/NaverThirdPartyLogin.framework/NaverThirdPartyLogin of architectures: armv7 i386 x86_64
Code Signing /Users/jangjinhyeog/Library/Developer/Xcode/DerivedData/beauket-aovymeokscfmzedgudszpmmcpehv/Build/Products/Debug-iphoneos/beauket.app/Frameworks/NaverThirdPartyLogin.framework with Identity Apple Development: jungsuk kim (88Y9Z3U74P)
/usr/bin/codesign --force --sign CC519E24BEBB1C043AAF86A880DA58A026AFB574 --preserve-metadata=identifier,entitlements ‘/Users/jangjinhyeog/Library/Developer/Xcode/DerivedData/beauket-aovymeokscfmzedgudszpmmcpehv/Build/Products/Debug-iphoneos/beauket.app/Frameworks/NaverThirdPartyLogin.framework’
/Users/jangjinhyeog/Downloads/beauket-ios-main/Pods/Target Support Files/Pods-beauket/Pods-beauket-frameworks.sh: line 42: source: unbound variable
Command PhaseScriptExecution failed with a nonzero exit code`

빌드시 이런 에러가 뜹니다 어떻게 해결해야할까요...

**Comment by HanBin-Kim** [comment]
안녕하세요.

최신버전 사용후 테스트 부탁드립니다.

감사합니다.
