### ISSUE TITLE
THIRDPARTYLOGIN_RECEIVE_TYPE.CANCELBYUSER always returned on iOS-running-on-M1-mac

### ISSUE THREAD

**Issue by keyOfVv** [naver/naveridlogin-sdk-ios#28]
SDK version: 4.1.5;
Host app: iOS app running on M1 mac (Apple Silicon) Ventura 13.4.1;
Xcode version: 14.2;
Reproduce step:
* call `NaverThirdPartyLoginConnection.requestThirdPartyLogin()`;
* a popup is presented, displaying: "My App" Wants to use "naver.com" to Sign In;
* click `Continue` button;
* delegate method `-oauth20Connection(_ oauthConnection:didFailAuthorizationWithReceive:)` get called with `receiveType` equals to `CANCELBYUSER`;

This issue only happens on M1 mac. Everything works as expected on iPhone/iPad;

**Comment by keyOfVv** [comment]
After updated SDK to **4.1.6**, above-mentioned issue is fixed, however:
- browser window can't be opened when using **Chrome** as default, 
- after setting Safari as default, every thing works fine;

Maybe some compatible works should be done for Chrome I suppose?

**Comment by keyOfVv** [comment]
Likely this issue is caused due to absent `callbackURLScheme` when creating `ASWebAuthenticationSession`.

**Comment by HanBin-Kim** [comment]
hello.

This issue was resolved in version 4.2.0.

thank you
