### ISSUE TITLE
Reason: image not found 오류

### ISSUE THREAD

**Issue by lowapple** [naver/naveridlogin-sdk-ios#4]
pod 로 dependency를 설정 후 실행시

dyld: Library not loaded: @rpath/NaverThirdPartyLogin.framework/NaverThirdPartyLogin
Reason: image not found

에러가 뜹니다. 이 문제는 어떻게 해결해야 하나요? 앱 삭제후 재설치 한 뒤 첫 실행시에만 에러가 뜨지 않고 두번째 부터는 이 에러가 뜨고 있습니다.

**Comment by HanBin-Kim** [comment]
안녕하세요.
프로젝트 설정 이나 cocoapods 설정의 문제로 보입니다.
현재 문의 주신 내용만으로는 정확하게 파악이 어렵습니다. 

1. pod cache clean naveridlogin-sdk-ios pod 캐시를 날린후
2. pod install 
3. 클린 (cmd+shift+option+k) 후 재빌드 한번 해주세요.

[링크](https://estebantorr.es/blog/2015/09/23/dyld-Library-not-loaded/)도 참조 해보시면 좋을것 같습니다.

적용이 잘 안되시면, 빌드 설정 및 pod 설정 파일을 보내주시면 다시 한번 답변 드리겠습니다.

**Comment by lowapple** [comment]
감사합니다. 해결되었습니다.
