### ISSUE TITLE
네이버앱 설치 안된 상태에서 로그인 시도시 다른앱(ZUMO) 호출 건

### ISSUE THREAD

**Issue by BlueMondays** [naver/naveridlogin-sdk-ios#7]
네이버앱이 설치가 안된 상태에서 로그인 시도시 타 앱이 호출됩니다.
분명 잘 됬었는데요..

네이버 개발자 포럼에 동일한 이슈 발생하는 게시글을 발견했습니다.
확인 후 빠른 피드백 바랍니다.
https://developers.naver.com/forum/posts/27984

**Comment by BlueMondays** [comment]
github에 최신 버전 업데이트 하고 나니 이슈 해결되었습니다.

**Comment by BlueMondays** [comment]
재발생하고있습니다.

**Comment by HanBin-Kim** [comment]
@BlueMondays 
안녕하세요. 
ZUMO엡에서 AppScheme관련하여 설정을 잘못해서 발생된 문제로, 
지난주 토요일 ZUMO앱 업데이트 이후에 발생하지 않고 있습니다.

감사합니다.
