### ISSUE TITLE
공사 추가 됐 다. NaverCafeSDK framework 과 NaverThirdPartyLogin. framework 뒤 네 이 버 의 cafe 로그인 효력 을 잃 게 된 다.

### ISSUE THREAD

**Issue by danwey** [naver/naveridlogin-sdk-ios#9]
공사 추가 됐 다. NaverCafeSDK framework 과 NaverThirdPartyLogin. framework 뒤 네 이 버 카페 의 등록 효력 을 잃 게 된 다.

**Comment by HanBin-Kim** [comment]
@danwey 
您好， 我觉得翻译不好正确。
请你，用中文或是英文再给我打字。谢谢你

**Comment by danwey** [comment]
没事了。解决了。谢谢

**Comment by HanBin-Kim** [comment]
@danwey 
Thank you.
